### ISSUE TITLE
Race between OnDataQueued and Accept event

### ISSUE THREAD

**Issue by tchardin** [filecoin-project/go-data-transfer#209]
### Context:
In the [changes](https://github.com/filecoin-project/go-data-transfer/commit/3a130c3f4d33e422b08a3175748e0c718156b6a5) I made, the provider may send the revalidation request voucher along with the initial response message in the same extension, essentially telling the client they accept the request + already asking for a payment voucher for the first block.
### Issue:
Although this seemed to work fine in my initial tests, I found an occasional race condition in which, on the provider side, the `OnPullDataSent` method of the revalidator is triggered _before_ the event subscriber sends the `Accept` event from the state machine. This results in the provider being unable to attribute the first bytes sent with any ongoing deal because the state machine doesn't know it's been accepted yet.
### Solution:
I've been trying a few things but I'm unable to figure out a reliable solution to this problem without significant refactor. Would love some pointers to figure out a solution I'm happy to implement. Thanks!
cc @dirkmc @hannahhoward

**Comment by dirkmc** [comment]
Thanks @tchardin I am going to take a look into this

**Comment by aarshkshah1992** [comment]
@dirkmc 

This is the "Graphsync hooks are synchronous" but the "Data transfer events fired by Graphsync hooks are async" problem as explained as a part of https://github.com/filecoin-project/lotus/issues/6343#issuecomment-851920012.

**Comment by dirkmc** [comment]
Makes sense Aarsh - I think the correct solution here is for Graphsync to ensure that the Accept event is always fired before calling the block queued hook.

**Comment by dirkmc** [comment]
@tchardin I'm trying to follow in the markets FSM the order in which the events you're describing occur.

Can you please provide us with a log showing the go-data-transfer and go-fil-markets states and events in the case where the revalidator OnPullDataSent is called before Accept fires. This will help us to track down exactly how we can fix the issue.

**Comment by dirkmc** [comment]
If you could turn on logging I think that would probably give us some clues as well.

You can do so by doing something similar to this:
https://github.com/filecoin-project/go-data-transfer/blob/f80db1711147ec0c4f41260ce71473167f9c7a55/impl/integration_test.go#L1939-L1943

In addition to the log subsystems in the code above, it would be helpful to see debug logs from the following subsystems:
- retrievaladapter
- retrieval
- markets-rtvl
- markets-rtvl-reval

Please rebase off of the latest master so the log lines line up 🙏

**Comment by tchardin** [comment]
@dirkmc I opened #219 to keep things simple and demonstrate what I mean. Let me know if that makes sense. Thanks!

**Comment by tchardin** [comment]
@dirkmc It's a clone of go-fil-markets which differs in that it doesn't return ErrPause but immediately starts sending blocks. 
I thought I could just set up tracking in ValidatePull too however the channel doesn't exist at this point so I have no way to tie it to the channel ID exposed in OnPullDataSent.

**Comment by dirkmc** [comment]
The channel does actually exist when ValidatePull is called, however we're not passing the Channel ID to ValidatePull so you're right that you can't start tracking at that point.

The fix we need to make here is to modify go-data-transfer to pass the Channel ID to ValidatePull (and we should also pass the Channel ID to ValidatePush for consistency).

**Comment by tchardin** [comment]
I tried to make those changes myself but it seems the pull is validated before creating the channel no? https://github.com/filecoin-project/go-data-transfer/blob/f80db1711147ec0c4f41260ce71473167f9c7a55/impl/events.go#L364-L379

**Comment by dirkmc** [comment]
acceptRequest() is called by OnRequestReceived() which already has a channel ID parameter:
https://github.com/filecoin-project/go-data-transfer/blob/f80db1711147ec0c4f41260ce71473167f9c7a55/impl/events.go#L128

**Comment by dirkmc** [comment]
I can make the change

**Comment by tchardin** [comment]
Great, thanks!

**Comment by dirkmc** [comment]
@tchardin could you try out https://github.com/filecoin-project/go-data-transfer/pull/220

**Comment by tchardin** [comment]
@dirkmc that's perfect! Ran a bunch of tests and it solves all my issues. Thanks

**Comment by dirkmc** [comment]
Great to hear 👍
