### ISSUE TITLE
When a graphsync transfer restarts, send "do-not-send-first-blocks" message

### ISSUE THREAD

**Issue by dirkmc** [filecoin-project/go-data-transfer#256]
When a graphsync transfer restarts (because the connection goes down, or because the node is bounced) the party receiving the data makes the same request, and uses an extension to indicate what data it has already received.

Currently the extension contains a list of all CIDs that the receiver already received. However some DAGs can contain so many blocks that the CID list becomes prohibitively long.

To address this problem a "do-not-send-first-blocks" extension will be added to graphsync. The extension allows the receiver to indicate the number of blocks it has received. Blocks are sent in a consistent order, so the sender can use the number of blocks received as an offset into the ordered list of blocks to be sent.

go-data-transfer needs to be updated to use this extension instead of "do-not-send-cids". This will require a protocol version bump.
go-data-transfer should continue to use the "do-not-send-cids" extension with peers using older versions of the protocol.

#### Proposed Implementation

Add method to `DataTransferNetwork` interface:
```
// Get the go-data-transfer protocol that the peer supports, connecting to the peer if necessary
Protocol(peer.ID) protocol.ID
```

Modify `Transport.OpenChannel()` interface to
- take a `ChannelState` instead of a `doNotSendCids` parameter
  Note that `ChannelState` has `ReceivedCids()` and `ReceivedCidsLen()` methods

In the graphsync implementation of `Transport`:
- Modify `NewTransport()` to take an interface that exposes `DataTransferNetwork`'s `Protocol(peer.ID) protocol.ID` method
- Modify `OpenChannel()`:
  if `ReceivedCidsLen()` > 0
    - switch on the peer's protocol ID
    - if the protocol is high enough, add a "do-not-send-first-blocks" extension
    - otherwise add the old "do-not-send-cids" extension

**Comment by hannahhoward** [comment]
seems reasonable

**Comment by hannahhoward** [comment]
follow-up: this makes it sounds like you want the extension to behave like "do-not-send-first-unique-blocks"

ReceivedCids is, if I remember, a set, which is different than I had in mind for how the extension would work. I can make it do the this, but it's gonna be harder to implement.

I had assumed data transfer would just have a block counter incrementing on each new called to DataReceived.

Anyway, I'm gonna see what I can do about implementing this, but I may need to the simpler version first.

**Comment by dirkmc** [comment]
That makes sense 👍 

Happy to do whatever makes the graphsync part easier, it's certainly not hard for us to keep an incrementing counter.
